// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uOyRNjiE6Za3HrG_ixgkl3_rhsc6IuM',
    appId: '1:620830095990:web:5edd768702d9bad8943d57',
    messagingSenderId: '620830095990',
    projectId: 'karak-74aa6',
    authDomain: 'karak-74aa6.firebaseapp.com',
    storageBucket: 'karak-74aa6.appspot.com',
    measurementId: 'G-TF1820N2CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw7awk459mt8CmQjTQlNQ3B0EuSyv4tD4',
    appId: '1:620830095990:android:77dcc7be66c31fcb943d57',
    messagingSenderId: '620830095990',
    projectId: 'karak-74aa6',
    storageBucket: 'karak-74aa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrhoYdjkd8Kx0k0-vAqS-l8edpwG_fpEY',
    appId: '1:620830095990:ios:5fa0c5fb99d84410943d57',
    messagingSenderId: '620830095990',
    projectId: 'karak-74aa6',
    storageBucket: 'karak-74aa6.appspot.com',
    iosBundleId: 'com.example.fbsocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrhoYdjkd8Kx0k0-vAqS-l8edpwG_fpEY',
    appId: '1:620830095990:ios:c7116828467610c1943d57',
    messagingSenderId: '620830095990',
    projectId: 'karak-74aa6',
    storageBucket: 'karak-74aa6.appspot.com',
    iosBundleId: 'com.example.fbsocial.RunnerTests',
  );
}
